### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xeodou** [uipoet/sublime-jshint#58]
I have install the jshint with sublime package control but got an error when use it.

```
[Errno 2] No such file or directory
[cmd:  [u'jshint', u'/xxx.js', u'--reporter', u'/Users/xxx/Library/Application Support/Sublime Text 2/Packages/JSHint/reporter.js']]
[dir:  xxx]
[path: /usr/local/share/npm/bin:/usr/local/bin:/opt/local/bin]
[Finished]
```

i think the error is `Application Support/Sublime Text 2` path with space in it and cmd can't run it correctly.

**Comment by johannakate** [comment]
maybe change the instructions from "When the plugin list appears, type jshint. Among the entries you should see SublimeLinter-jshint. If that entry is not highlighted, use the keyboard or mouse to select it."

to 

When the plugin list appears, type SublimeLinter-jshint

**Comment by geoidesic** [comment]
@TheDeveloper why `SublimeLinter-jshint` and not `jshint`? 
The second option looks better here: http://smoothprogramming.com/sublime-text/configure-jshint-sublime-text-code-quality/
... but I can't get it to work either despite installing it via npm and / or brew.

**Comment by geoidesic** [comment]
Please do this pull request: it fixes this issue for mac users.
https://github.com/uipoet/sublime-jshint/pull/76/commits/010afc6251ac3eafdc4cb3433f013f1b543e0147
